# Generated by Django 5.0.6 on 2026-06-07 06:07

import django.utils.timezone
import resume_parser.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('required_skills', models.JSONField(default=list, help_text='List of skill names required for this role')),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text='List of preferred skill names')),
                ('min_experience', models.IntegerField(default=0, help_text='Minimum years of experience')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=resume_parser.models.resume_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('parsed_text', models.TextField(blank=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience_list', models.JSONField(blank=True, default=list)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('keyword_score', models.FloatField(blank=True, null=True)),
                ('format_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('education_score', models.FloatField(blank=True, null=True)),
                ('skills_match_score', models.FloatField(blank=True, null=True)),
                ('suggested_roles', models.JSONField(blank=True, default=list)),
                ('match_scores', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Language'), ('framework', 'Framework / Library'), ('database', 'Database'), ('cloud', 'Cloud / DevOps'), ('tool', 'Tool / Platform'), ('soft_skill', 'Soft Skill'), ('domain', 'Domain Knowledge'), ('language', 'Language')], max_length=50)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names for this skill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
