# Generated by Django 5.0.6 on 2026-06-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content_distribution_score',
            field=models.FloatField(blank=True, help_text='Score for how well content is balanced across resume sections', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='section_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed section detection and quality analysis data'),
        ),
    ]
