# Generated by Django 5.0.6 on 2026-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0002_resume_content_distribution_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='improvement_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Actionable suggestions to improve the resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects_list',
            field=models.JSONField(blank=True, default=list, help_text='Extracted project entries from resume'),
        ),
    ]
